=== future0143/task4_1_7/src/test/resources/response_positive_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "id": {
      "type": "integer"
    },
    "firstName": {
      "type": "string"
    },
    "lastName": {
      "type": "string"
    },
    "phoneNumber": {
      "type": "string",
      "pattern": "^\\+7[0-9]{10}"
    },
    "email": {
      "type": ["string", "null"]
    },
    "dateOfBirth": {
      "type": ["string", "null"]
    },
    "loyalty": {
      "type": "object",
      "properties": {
        "bonusCardNumber": {
          "type": "string"
        },
        "status": {
          "type": "string"
        },
        "discountRate": {
          "type": "integer"
        }
      },
      "required": [
        "bonusCardNumber",
        "status",
        "discountRate"
      ]
    },
    "shopCode": {
      "type": ["string", "null"]
    },
    "updatedAt": {
      "type": "string"
    },
    "createdAt": {
      "type": "string"
    }
  },
  "required": [
    "firstName",
    "lastName",
    "phoneNumber"
  ]
}

=== future0143/task4_1_7/src/main/resources/request/post_request/create-customer-all-fields.json
{
  "id": 0,
  "firstName": "Ivan",
  "lastName": "Petrov",
  "phoneNumber": "+78905927238",
  "email": "ivanpetr@mail.ru",
  "dateOfBirth": "2020-09-11",
  "loyalty": {
    "bonusCardNumber": "string",
    "status": "string",
    "discountRate": 0
  },
  "shopCode": null,
  "updatedAt": "2023-09-11T13:36:52.372Z",
  "createdAt": "2023-09-11T13:36:52.372Z"
}
